### ISSUE TITLE
Logs not compatible with parser

### ISSUE THREAD

**Issue by jan25** [irajdeep/go-and-watch#3]
Check if logs are in common fmt. Check with parser what it expects

**Comment by irajdeep** [comment]
Okay I tried to reproduce the issue. 
Sample log line from current parser
> 127.0.0.1 - - [24 Oct 18 21:33 +0200] "POST /getIdentifier HTTP/1.1" 400 301 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"

Sample common log format line
> 77.179.66.156 - - [25/Oct/2016:14:49:33 +0200] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"

Other than the time I don't see any difference. The time formatting is not a blocker IIRC.
Am I missing something ?

**Comment by jan25** [comment]
this is somehow not compatible with axsparser https://godoc.org/github.com/Songmu/axslogparser

**Comment by irajdeep** [comment]
What and why does it complain about? 
Can you paste logs / trace ?

**Comment by jan25** [comment]
`failed to parse apachelog (not matched): 45.153.83.165 - Carroll6784 743 [2018-10-22T22:06:32+02:00] "POST getIdentifier HTTP/1.1" 502 17842`

**Comment by jan25** [comment]
Let me fix this
